### ISSUE TITLE
Information on measurements and benchmarks

### ISSUE THREAD

**Issue by gaganso** [SEALABQualityGroup/icpe-data-challenge-jmh#1]
Thank you for this dataset! I see that the information on the different benchmarking applications is provided here - [benchmarks](https://github.com/SEALABQualityGroup/icpe-data-challenge-jmh/blob/main/benchmarks_revision.csv). Can you please provide more information on the measurements being collected? Is it always latency? The file names in the "timeseries" folder seem to convey some additional information considering they all have the same naming convention. Can you please provide more information on the naming convention and how we can interpret them?

**Comment by mtucci** [comment]
Hi @gaganso,

> I see that the information on the different benchmarking applications is provided here - [benchmarks](https://github.com/SEALABQualityGroup/icpe-data-challenge-jmh/blob/main/benchmarks_revision.csv).

Yes, in that file you can find the name of the repository and the revision (tag) at which the benchmarks were executed.

> Can you please provide more information on the measurements being collected? Is it always latency?

All the benchmarks are executed in the JMH [SampleTime mode](https://github.com/openjdk/jmh/blob/7708484728b73b8ceed8b71dd3068010d588173e/jmh-samples/src/main/java/org/openjdk/jmh/samples/JMHSample_02_BenchmarkModes.java#L99). The full command line is:
`-bm sample -wi 0 -i 3000 -f 10 -r 100ms`, meaning:
- `-bm sample`: SampleTime mode. This collects samples of execution time. You can access the raw histograms of these samples by downloading the [package](https://zenodo.org/record/5961018) containing the JMH output files.
- `-wi 0`: Number of warmup iterations. We didn't want JMH to remove any warmup iteration because we wanted to detect the warmup phase ourselves.
- `-i 3000`: Number of measurement iterations.
- `-f 10`: Number of forks.
- `-r 100ms`: Minimum time to spend at each measurement iteration. Benchmarks may generally run longer than iteration duration.

The time series you can find in the [timeseries](../blob/main/timeseries) folder are computed on the basis of the raw JMH measurements. The JSON files in that folder contain 10 time series, one for each fork. Each datapoint in a time series is the mean of the samples collected for each consecutive iteration. Therefore, each datapoint represents the mean execution time in seconds for a benchmark iteration.

> The file names in the "timeseries" folder seem to convey some additional information considering they all have the same naming convention. Can you please provide more information on the naming convention and how we can interpret them?

The naming convention in the _timeseries_ folder is:
`<github_organization>__<github_project>#<benchmark_method>#<benchmark_parameters>.json`
However, you could use the `Benchmark` class in the [example_viz.py](../blob/main/example_viz.py) script to take care of the parsing, so that you can access the information through the fields of that object.

If you wonder where the values for the parameters come from, they were randomly selected among the possible valid values for each specific benchmark.

**Comment by gaganso** [comment]
Thank you for the detailed response! This description along with the example_viz.py script provides a clear picture of the data. 

(Adding a link for what [fork](https://stackoverflow.com/questions/35046745/what-is-the-purpose-of-jmh-fork) means in JMH for someone new to JMH like me.)
